version: "3"
services:
  installer:
    environment:
      - ENV_DESCRIPTION=default,local
  nginx:
    environment:
      - ENV_DESCRIPTION=default,local
    ports:
      - "8000:8000"
      - "8001:8001"
  js_dev_builder:
    #ports:
     # - 8888:8888
    environment:
      - PHP_WEB_BUGS_BASE_URL=http://local.api.jssadness.com
  php_fpm:
    environment:
      - ENV_DESCRIPTION=default,local
  php_fpm_debug:
    environment:
      - ENV_DESCRIPTION=default,local
  varnish:
    depends_on:
      - nginx
      - php_fpm
      - php_fpm_debug
    ports:
      - "80:80"
    environment:
      - ENV_DESCRIPTION=default,local


