version: "3"
services:
  installer:
    build: containers/installer
    environment:
      - COMPOSER_CACHE_DIR=/var/app/var/cache/composer
      - COMPOSER_ALLOW_SUPERUSER=1
    networks:
      default_network:
    volumes:
      - .:/var/app
  js_dev_builder:
    build: containers/js_dev_builder
    volumes:
      - .:/var/app
  sass_dev_builder:
    build: containers/sass_dev_builder
    volumes:
      - .:/var/app
  php_fpm:
    build: containers/php_fpm
    image: jssadness_php_fpm
    environment:
      - COMPOSER_CACHE_DIR=/var/app/var/cache/composer
      - COMPOSER_ALLOW_SUPERUSER=1
    networks:
      default_network:
    volumes:
      - .:/var/app
  php_fpm_debug:
    build: containers/php_fpm_debug
    environment:
      - COMPOSER_CACHE_DIR=/var/app/var/cache/composer
      - COMPOSER_ALLOW_SUPERUSER=1
      - PHP_IDE_CONFIG="serverName=PHP_OPENDOCS_DEBUG"
    depends_on:
      - php_fpm
    networks:
      default_network:
    volumes:
      - .:/var/app
  nginx:
    build: containers/nginx
    depends_on:
      - php_fpm
    volumes:
      - .:/var/app
    networks:
      default_network:
        aliases:
          - internal.jssadness.com
  redis:
    image: redis:6.0.10
    volumes:
      - .:/var/app
    command: ["redis-server", "/var/app/containers/redis/config/redis.conf"]
    networks:
      default_network:
  varnish:
    build: containers/varnish
    environment:
      CACHE_SIZE: 128m
    networks:
      default_network:
    volumes:
      - ./:/var/app
    depends_on:
      - nginx
      - php_fpm
networks:
  default_network:

