version: "3"
services:
  installer:
    environment:
      - ENV_DESCRIPTION=default,prod
  npm_build:
    build: containers/js_dev_builder
    environment:
      # we don't set NODE_ENV as production, as that is for serving node requests, not building stuff.
      - PHP_WEB_BUGS_BASE_URL=https://api.jssadness.com
      - ENV_DESCRIPTION=default,prod

    volumes:
      - .:/var/app
  php_fpm:
    environment:
      - ENV_DESCRIPTION=default,prod
  varnish:
    depends_on:
      - nginx
      - php_fpm
    ports:
      - "8007:80"
    environment:
      - ENV_DESCRIPTION=default,prod